// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using clientes_api.Data;

#nullable disable

namespace clientes_api.Migrations;

[DbContext(typeof(ClientContext))]
partial class ClientContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "7.0.10")
            .HasAnnotation("Relational:MaxIdentifierLength", 64);

        modelBuilder.Entity("clientes_api.Models.Client", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<string>("Cep")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<string>("Cidade")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<string>("Complemento")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<string>("Cpf")
                    .IsRequired()
                    .HasMaxLength(11)
                    .HasColumnType("varchar(11)");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<string>("Logradouro")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<string>("NomeCompleto")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<string>("NumeroLogradouro")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<string>("SiglaUf")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.HasKey("Id");

                b.ToTable("Clients");
            });
#pragma warning restore 612, 618
    }
}
